### PR TITLE
Support bytes in settings.SECRET_KEY on Python 3.

### PR DESCRIPTION
**Pull request by fyber**
My previous PR https://github.com/edx/django-oauth2-provider/pull/48 was built on assumption that `settings.SECRET_KEY` is always `bytes`. But reading the [documentation](https://docs.djangoproject.com/en/1.11/ref/settings/#secret-key) I just realized that it is not always true:

> Uses of the key shouldn’t assume that it’s text or bytes. Every use should go through force_text() or force_bytes() to convert it to the desired type.

So I added `force_bytes()` around usages of `settings.SECRET_KEY`.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @fyber! I've created [OSPR-1971](https://openedx.atlassian.net/browse/OSPR-1971) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/django-oauth2-provider/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@fyber Thanks.  We should straighten out your contributor agreement.  Have you signed one?

**Comment by fyber** [comment]
@nedbat Sorry, I forgot to do that previous time. I just signed and sent it to legal@edx.org.

**Comment by nedbat** [comment]
@fyber, thanks. We have your contributor agreement.

**Comment by nedbat** [comment]
@clintonb @jmbowman Who would be the right person to review this?

**Review by clintonb — COMMENTED** [review]
Can you provide a test to prove this fixes the issue?

**Comment by fyber** [comment]
@clintonb I've just updated the PR.
I also put `python_2_unicode_compatible` decorator on models to make it possible to use `__str__` both on py2 and py3.

**Review by clintonb — APPROVED** [review]
Thanks for also keeping your commits clean and focused on a single issue. Beautiful!

**Pull request merged**
