### PR TITLE
WIP WL-286 Support multiple redirect URIs for a single client

### PR DESCRIPTION
**Pull request by douglashall**
We need to support LMS/Otto single sign-on for sites with custom domains. This change adds this support by allowing for multiple redirect URIs to be configured for a single Client.

Related PR:
https://github.com/edx/edx-platform/pull/11431

### CODE REVIEW

**Comment by douglashall** [comment]
@clintonb @jimabramson Can you provide feedback on the approach taken here to support SSO when multiple domains are in play for a single client?

**Comment by clintonb** [comment]
1. What are the risks of making this change?
2. What are the costs of moving to one client per domain?

**Comment by douglashall** [comment]
1. I am not aware of any risk that this change would introduce. It would be great to get input from others on this question though.
2. We would need to modify the python-social-auth client library which Otto uses to perform the OAuth handshake which seems considerably more involved and semantically incorrect.

**Comment by clintonb** [comment]
What about man-in-the-middle attacks? What if malicious code changes the `redirect_uri` value before it reaches the server? There needs to be some form of validating the value to protect against this attack vector.

**Comment by douglashall** [comment]
Hmm. I'm not seeing how these changes open that attack vector. Can you elaborate?

**Comment by clintonb** [comment]
Let's take a step back. Where is this request being initiated, client-side or server-side?

**Comment by douglashall** [comment]
Client-side.

**Comment by clintonb** [comment]
Okay. Say I injected JavaScript that changed redirect_uri to
http://my-evil-site.org? What prevents the library from redirecting there?

**Comment by douglashall** [comment]
What would prevent the library from redirecting to a malicious site without these changes?

**Comment by clintonb** [comment]
Today redirect_uri is set on the `Client` model: https://github.com/edx/django-oauth2-provider/blob/edx/provider/oauth2/models.py#L47.

**Comment by douglashall** [comment]
This does not change that. We are just using the passed redirect_uri parameter as an additional query parameter when looking for the correct client so that we can distinguish between Client models for a given client application.

**Comment by clintonb** [comment]
I'm confused. If you use the redirect_uri solely for lookup, the user will be redirected to the site for the original domain. In the case of multi-tenancy, this will result in a user coming from ecommerce.acme.edx.org being redirected to ecommerce.edx.org. This will result in improper branding.

What I have seen done, and thought you were doing, is allowing the client to specify the `redirect_uri`. To prevent MITM attacks, the OAuth provider validates the redirect_uri. If validation fails, the user is sent to an error page. If validation succeeds, the user is sent to the given redirect_uri.

**Comment by douglashall** [comment]
Right, the `redirect_uri` is still being validated here by the OAuth provider, in fact, sooner in the request cycle because we use it to find the Client model.

The oauth2_client table will look something like:

```
+----------------------------------------------+-----------------------------------------------------------------+---------------+
| url                                          | redirect_uri                                                            | client_id     |
+----------------------------------------------+-----------------------------------------------------------------+---------------+
| http://edx.org:8002                          | http://edx.org/complete/edx-oidc/                          | ecommerce-key |
| http://acme.edx.org:8002                | http://acme.edx.org:8002/complete/edx-oidc/       | ecommerce-key |
+----------------------------------------------+-----------------------------------------------------------------+---------------+
```

Client requests will contain the `client_id` and `redirect_uri` for the given client. We will use these values to validate that this is a known client request by querying the client table using both client_id and `redirect_uri`. The request signature will be validated using the shared `client_secret`. If we have a valid request we will redirect to `redirect_uri`.

**Comment by clintonb** [comment]
Why have multiple clients and do these lookups? The OAuth 2.0 spec includes this functionality. It just hasn't been implemented.
- https://tools.ietf.org/html/rfc6749#section-4.1
- https://tools.ietf.org/html/rfc6749#section-10.6

Note that @nasthagiri and @jcdyer are looking into replacing this library with [django-oauth-toolkit](https://github.com/evonove/django-oauth-toolkit); however, that's probably a month, or more, from production.

**Comment by douglashall** [comment]
The change would effectively offer the same implementation that django-oauth-toolkit does wrt multiple redirect URIs per client. I'm all for trading this library for another that has feature parity and better support, but it sounds like that effort will not be done in time for the needs of our upcoming white label offerings. This is a fairly targeted and simple solution to the current problem in my view.

It sounds like we've at least gotten past the security concerns you were raising earlier. Do you concur?

**Comment by douglashall** [comment]
@clintonb I thought a little more about our decision to stick multiple redirect URIs in the `Client.redirect_uri` field and now I'm feeling like that is a bit messy compared to this current change. Can we talk more about your reservations regarding having multiple client records with the same `client_id` and different `redirect_uri` fields? Multiple `Client` records feels like a cleaner implementation than a comma-delimited list in a CharField. Apologies for the flip-flopping.

**Comment by clintonb** [comment]
That one field may seem messy; but, the alternative includes extraneous data in the database. If you modify the usage of the `redirect_uri` field, we (1) maintain the idea of one row per client, and (2) get a head start on updating edx/configuration to create a single client with multiple redirect URIs.

If we go down the path of having "ghost clients" you end up with (1) dirty data, and (2) the need to update configuration to create these ghost clients, if necessary, for testing on sandboxes.

**Comment by douglashall** [comment]
@clintonb Good point regarding operational concerns. If they didn't exist, I think the optimal solution would be a new `ClientRedirectUri` model. But alas...

Okay, I will modify `Client.redirect_uri` to be a CharField and handle the condition when it contains multiple redirect URIs. Thanks again.

**Comment by clintonb** [comment]
Use a `TextField`, rather than `CharField`, to avoid issues with character
limits as we add more tenants.

**Comment by douglashall** [comment]
@clintonb I think we are good here once the checks complete. Thanks for your help on this. Let me know if there is anything else you think should be addressed.

**Comment by douglashall** [comment]
@jcdyer I heard you are working in this package as well. Just wanted to give a heads up in case this affects anything on your end.

**Comment by douglashall** [comment]
FYI @mattdrayer @mjfrey

**Comment by douglashall** [comment]
@clintonb @mattdrayer It turns out I think we are going to have to go back to the drawing board on this one. This change will not fully support the current white label problem we are trying to solve because the client will still only have a single OAuth provider URL to send users over to for authentication. This means if the user is prompted to log in they will not get the site-specific login page. I think the only way to do this is to modify our OAuth client to be site-aware. Hopefully more to come soon.

**Pull request closed without merging**
