### PR TITLE
Migrations out-sync with models.  TNL-4296

### PR DESCRIPTION
**Pull request by muzaffaryousaf**
https://openedx.atlassian.net/browse/TNL-4296

The purpose of this PR to make the migrations in sync with models, for that purpose we have added unit test to check if migrations are in sync with models. Test will fail if they are not.

### CODE REVIEW

**Comment by muzaffaryousaf** [comment]
@jcdyer The migrations for oauth app are out of sync, in history you were the last person to add `related_name` to the model fields, i've added the missing migration, Does this make sense to you ? 
Thanks.
@symbolist Look ?

**Comment by jcdyer** [comment]
Yes, that looks correct.  I didn't realize the change needed a migration, as it pertains only to the model level, but doesn't (or at least shouldn't) actually affect the DB schema.  Thanks for cleaning this up.

I don't see the unittest that finds the problem, though.  Is that in a different PR?

**Comment by muzaffaryousaf** [comment]
@jcdyer The test is in platform https://github.com/edx/edx-platform/pull/11949

**Comment by symbolist** [comment]
:+1:

**Pull request merged**
