### PR TITLE
Add multicolumn index on expires

### PR DESCRIPTION
**Pull request by jbarciauskas**
For https://openedx.atlassian.net/browse/PLAT-1062 - add a multicolumn index to fix slow query on oauth2_grants table

@clintonb @jmbowman

### CODE REVIEW

**Comment by jbarciauskas** [comment]
There might be a case to be made to add an index on expires as well, to make future deletes faster?

**Comment by clintonb** [comment]
👍

**Review by clintonb — APPROVED** [review]

**Comment by clintonb** [comment]
I agree with indexing the expires column. Depending on the size of the table, it may be faster to clear expired rows first before attempting to index them.

**Comment by jbarciauskas** [comment]
It's going to do a full table scan either way, right? Just the indexing operation would be faster. I'd hesitate to add a custom migration, but maybe just open a devops ticket to take a whack at it before the release?

**Comment by clintonb** [comment]
Right. No data migration. SQL FTW.

**Comment by jmbowman** [comment]
Should add the migration to actually create the new index.

**Comment by jbarciauskas** [comment]
Alright, added indexes on the expires field on both the Grant and AccessToken models, as well as the multi-column index, to aid in future trimming. Also added the migrations file @jmbowman

**Comment by jmbowman** [comment]
👍

**Pull request merged**
