### PR TITLE
Bump version to 1.3.5

### PR DESCRIPTION
**Pull request by shadinaif**
This is required to complete the work on an **edx-platform PR** https://github.com/edx/edx-platform/pull/18875 ; which was created to close **INCR-8** issue https://openedx.atlassian.net/browse/INCR-8

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @shadinaif! I've created [OSPR-2607](https://openedx.atlassian.net/browse/OSPR-2607) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by shadinaif** [comment]
@doctoryes , @OmarIthawi ; your reviews please :)

**Review by OmarIthawi — APPROVED** [review]
LGTM, Thanks @shadinaif!

**Review by doctoryes — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@shadinaif 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/django-oauth2-provider&entry.867055334=https://github.com/edx/django-oauth2-provider/pull/57&entry.1484655318=https://github.com/shadinaif&entry.752974735=2018-09-12+08:45&entry.1917517419=2018-09-12+20:03&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by doctoryes** [comment]
Thanks, @shadinaif !

**Comment by shadinaif** [comment]
Thank you @doctoryes and @OmarIthawi

**Pull request merged**
