### PR TITLE
Fix migrations compability with Python 3

### PR DESCRIPTION
**Pull request by Skyross**
Fix migrations capability with Python 3.
Update tox.ini with migration checks.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Skyross! I've created [OSPR-2026](https://openedx.atlassian.net/browse/OSPR-2026) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/django-oauth2-provider/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@Skyross thanks for this pull request! Let us know when you have sent in your contributor agreement so that we can start reviewing it.

**Comment by Skyross** [comment]
@nedbat, where (which email) I should send this signed contributor agreement?

**Comment by Skyross** [comment]
@nedbat I've sent signed contributor agreement today. Please check the legal email.

**Comment by nedbat** [comment]
@Skyross Thanks, I've received your agreement.

**Comment by nedbat** [comment]
@edx/platform-team Can you take this one?

**Review by macdiesel — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@Skyross 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/django-oauth2-provider&entry.867055334=https://github.com/edx/django-oauth2-provider/pull/51&entry.1484655318=https://github.com/Skyross&entry.752974735=2017-11-28+23:08&entry.1917517419=2017-12-11+22:47&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by Skyross** [comment]
Thanks!
Btw. When you plan to create a new tag with the release on PyPI?
Any draft estimations are good for me too.

**Comment by macdiesel** [comment]
@Skyross I opened PR #52 and have pushed a new tag. You should see it soon.

**Pull request merged**
