### PR TITLE
allow 1.9

### PR DESCRIPTION
**Pull request by yeago**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @yeago! I've created [OSPR-1390](https://openedx.atlassian.net/browse/OSPR-1390) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/django-oauth2-provider/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by gsong** [comment]
@yeago Currently the entire edX platform runs on Django 1.8. Can you tell us a bit more about your use case for going to Django 1.9, it'll help us determine if this is something we should consider incorporating.

By the way, please submit a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) to us so we can accept this pull request. We realize it's additional work for a simple change in this case, but we're hoping you would make future contributions as well.

**Comment by openedx-webhooks** [comment]
Hello @yeago: We are unable to continue with review of your submission at this time. Please see the associated JIRA ticket for more explanation.

**Comment by clintonb** [comment]
I second @gsong's request for more details. Additionally, adding support for Django >1.8 will require updating this package to use `tox` to test all supported combinations.

**Comment by yeago** [comment]
No idea what you really are asking. You want a "case" to use Django 1.9? This package works fine in 1.9 so all this PR does is relax that requirement to allow setup scripts to not chokedie when using this lib.

**Comment by clintonb** [comment]
@yeago this package is only intended to be used with edx/edx-platform, which does not support Django 1.9. So, yes, a case needs to be made to support Django 1.9 for this package. Additionally, we want to migrate away from this package toward django-oauth-toolkit.

**Comment by yeago** [comment]
i have NFI what edx-platform is I was just pushing fixes to this since it seemed to be relatively up to date. will ignore in future. thank you.

**Pull request closed without merging**
