### PR TITLE
Django2.2 Support

### PR DESCRIPTION
**Pull request by Ayub-Khan**
-Updated Requirements management
-updated tox
-updated setup.py

### CODE REVIEW

**Comment by jmbowman** [comment]
We're actually hoping to drop support for this package very soon; can we put this work (and any other PRs depending on it) on pause for a bit?  I want to see if we can drop our dependency on this in the next week or two.

**Comment by Ayub-Khan** [comment]
sure np.

**Comment by Ayub-Khan** [comment]
@jmbowman any update on this.

**Comment by jmbowman** [comment]
The work to remove our dependency on this was started in the last couple of days, the tentative plan is to have it done by the end of December.  I think we're still good with just leaving this alone while we get the rest of the dependencies updated.

**Comment by Ayub-Khan** [comment]
@jmbowman any update on this.

**Comment by jmbowman** [comment]
Progress stalled for a while during the holidays, but Robert is working on it in [BOM-897](https://openedx.atlassian.net/browse/BOM-897); Insights is the last service using this old authentication method, once it's updated we should be able to get rid of this.

**Comment by Ayub-Khan** [comment]
@jmbowman it seems  BOM-897 is done. should we close this.

**Comment by jmbowman** [comment]
The definitive ticket to wrap up the removal of this from edx-platform is now [BOM-1161](https://openedx.atlassian.net/browse/BOM-1161).  It's not quite done yet, but we expect to get it there within a week.  Should be safe to go ahead and close this PR.

**Pull request closed without merging**
