### PR TITLE
Bump version to 1.2.2

### PR DESCRIPTION
**Pull request by doctoryes**
Purpose: to make the new management command easily runnable by putting it in an installable package.

Part of: https://openedx.atlassian.net/browse/PLAT-1674

### CODE REVIEW

**Comment by jibsheet** [comment]
If 1.2.0 adds the migration and 1.2.2 adds the management command to shrink the table, what's our plan to get the management command out to prod before the migration runs?

**Comment by doctoryes** [comment]
@jibsheet I was hoping for some guidance on that point. This change will at least make the module installable - so I was thinking we boot up a temporary current AMI, upgrade DOP to 1.2.2 in its edxapp venv, and run the mgmt command there. How does that sound?

**Comment by jibsheet** [comment]
@doctoryes We can probably do something like that (run it off of an admin box with an edxapp venv) - in an ideal world we'd have a release that only contained the management command followed by a release with the compat/migration so that can run out in a normal process.  How hard would that be to arrange?  I assume it'd have to be some reverts to master and later remerges, or tagging/releasing from a branch?  It would cause the least manual process since we could just run it on a normal prod-edx-worker machine.

It would also help close followers downstream of master (and hawthorne folks) since they can do a staggered upgrade also.

**Comment by doctoryes** [comment]
@jibsheet It'd be a two-day (+?) dance including:
- Create a branch off DOP 1.1.4.
- Commit/push the management command, get PR merged, and tag.
- Change the edx-platform requirement to a Github req and get PR merged.
- Post-release, *manually* go run the mgmt command.
- Upgrade edx-platform to use the 1.2.2 version (the result of this PR), removing the GitHub req.
- Get that PR merged.
- Let the automatic process handle the rest.

There's still a manual step above. Is it difficult to create a throw-away admin box? Aside from that creation, the manual steps involved with that course of action are practically the same as the manual step above.

**Comment by jibsheet** [comment]
@doctoryes I guess that's fine, it's manual all the way around.  For future work like this, if we can stagger the releases that's how ops normally plans it when we make such a change (then it's just "boot an AMI in a protected place and run the command" rather than "boot a special machine that you're going to run pip on")

You'll want to talk to Fred/Feanil about a ticket for the running of the command, not sure if it needs to be a small ops ticket or can fit in devops.

**Review by jibsheet — APPROVED** [review]

**Review by bmedx — APPROVED** [review]

**Comment by doctoryes** [comment]
@jibsheet Thanks - I agree that we should get this ordering correct in the future. The django-oauth2-toolkit interestingly puts the token removal code right in with the model code:
https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/models.py#L373-L394
In the cases where models are being created that will expire and become useless, we should start insisting on that sort of clean-up code being present from the beginning.

**Comment by jibsheet** [comment]
@doctoryes agreed - if we show up early enough in the code process to provide design help, we generally ask for it.  I forget Feanil's exact phrasing, but something like "think about the lifecycle of this data".

**Pull request merged**
