### PR TITLE
Add mgmt cmd to delete expired access and refresh tokens

### PR DESCRIPTION
**Pull request by bmedx**
Uses the same methodology that was successful for deleting Grants.

### CODE REVIEW

**Comment by jibsheet** [comment]
FYI @edx/devops since one of us will be running this eventually

**Comment by jdmulloy** [comment]
@jibsheet @edx/devops what is the syntax for running this command?

**Comment by feanil** [comment]
@jdmulloy it's a management command.  The name of the command is the same as the python file which defines it but without the `.py` suffix.  It should have corresponding help data but you can also read the help in the file itself.  It looks like this one, takes a chunk size and a sleep interval.

**Review by jibsheet — APPROVED** [review]

**Comment by doctoryes** [comment]
👍

**Pull request merged**
